<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"补贴管理",
                        "menuJump":"列表",
                        "tableName":"butie"
                    }
                ],
                "menu":"补贴管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"成果管理",
                        "menuJump":"列表",
                        "tableName":"chengguo"
                    }
                ],
                "menu":"成果管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"打卡管理",
                        "menuJump":"列表",
                        "tableName":"daka"
                    }
                ],
                "menu":"打卡管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"补贴类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryButie"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"成果类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChengguo"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"考试类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKaoshi"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"培训项目类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryPeixunxiangmu"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"材料类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryPeixunxiangmuCailiao"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"证书类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhengshu"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"考试管理",
                        "menuJump":"列表",
                        "tableName":"kaoshi"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"考试成绩管理",
                        "menuJump":"列表",
                        "tableName":"chengji"
                    }
                ],
                "menu":"考试管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"培训项目管理",
                        "menuJump":"列表",
                        "tableName":"peixunxiangmu"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "审核",
                            "修改",
                            "删除"
                        ],
                        "menu":"培训项目报名管理",
                        "menuJump":"列表",
                        "tableName":"peixunxiangmuBaoming"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"培训项目材料管理",
                        "menuJump":"列表",
                        "tableName":"peixunxiangmuCailiao"
                    }
                ],
                "menu":"培训项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"证书管理",
                        "menuJump":"列表",
                        "tableName":"zhengshu"
                    }
                ],
                "menu":"证书管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"再就业人员管理",
                        "menuJump":"列表",
                        "tableName":"renyuan"
                    }
                ],
                "menu":"再就业人员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"老师管理",
                        "menuJump":"列表",
                        "tableName":"laoshi"
                    }
                ],
                "menu":"老师管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"补贴管理",
                        "menuJump":"列表",
                        "tableName":"butie"
                    }
                ],
                "menu":"补贴管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"成果管理",
                        "menuJump":"列表",
                        "tableName":"chengguo"
                    }
                ],
                "menu":"成果管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"打卡管理",
                        "menuJump":"列表",
                        "tableName":"daka"
                    }
                ],
                "menu":"打卡管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"考试管理",
                        "menuJump":"列表",
                        "tableName":"kaoshi"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"考试成绩管理",
                        "menuJump":"列表",
                        "tableName":"chengji"
                    }
                ],
                "menu":"考试管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"培训项目管理",
                        "menuJump":"列表",
                        "tableName":"peixunxiangmu"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"培训项目报名管理",
                        "menuJump":"列表",
                        "tableName":"peixunxiangmuBaoming"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"培训项目材料管理",
                        "menuJump":"列表",
                        "tableName":"peixunxiangmuCailiao"
                    }
                ],
                "menu":"培训项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"证书管理",
                        "menuJump":"列表",
                        "tableName":"zhengshu"
                    }
                ],
                "menu":"证书管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"老师",
        "tableName":"laoshi"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"补贴管理",
                        "menuJump":"列表",
                        "tableName":"butie"
                    }
                ],
                "menu":"补贴管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"成果管理",
                        "menuJump":"列表",
                        "tableName":"chengguo"
                    }
                ],
                "menu":"成果管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除"
                        ],
                        "menu":"打卡管理",
                        "menuJump":"列表",
                        "tableName":"daka"
                    }
                ],
                "menu":"打卡管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"考试管理",
                        "menuJump":"列表",
                        "tableName":"kaoshi"
                    }
					,
					{
                        "buttons":[
                            "查看"
                        ],
                        "menu":"考试成绩管理",
                        "menuJump":"列表",
                        "tableName":"chengji"
                    }
                ],
                "menu":"考试管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"培训项目管理",
                        "menuJump":"列表",
                        "tableName":"peixunxiangmu"
                    }
					,
					{
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"培训项目报名管理",
                        "menuJump":"列表",
                        "tableName":"peixunxiangmuBaoming"
                    }
                ],
                "menu":"培训项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"证书管理",
                        "menuJump":"列表",
                        "tableName":"zhengshu"
                    }
                ],
                "menu":"证书管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"再就业人员",
        "tableName":"renyuan"
    }
];

var hasMessage = '';
